rename_keep_dict = {
'Hospital_cat': ['hospital_code', True],
 'HospitalName_EN_cat': ['hospital_name', True],
 'UnitName_cat': ['unit_category', True],
 'SeverityLevelToStopOrder_cat': ['severity_level_to_stop_order', True],
 'Medical_Record': ['medical_record', True],
 'Admission_No': ['admission_num', True],
 'AGE_num': ['age', True],
 'Gender_Text_EN_cat': ['gender', True],
 'SectorText_EN_cat': ['sector', True],
 'Time_Prescribing_Order': ['time_prescribing_order', True],
 'Drug_Header_cat': ['alert_drug_header', True],
 'Module_Alert_Rn': ['module_alert_rn', True],
 'Alert_Message': ['alert_message', True],
 'Alert_Severity': ['alert_severity', True],
 'OrderOrigin': ['order_origin', True],
 'ShiftType_cat': ['shift_type', True],
 'DayEN_cat': ['day', True],
 'HospAmount_new': ['currentyl_hospitalized', True],
 'NumMedAmount': ['num_med_order', True],
 'Other_Text': ['response_reasons_other_text', True],
 'ResponseType_cat': ['response_type', True],
 'Details': ['order_details', True],
 'Basic_Name': ['drug_name_order', True],
 'DiagnosisInReception': ['chronic_diagnosis', True],
 'HospDiagnosis': ['hospital_diagnosis', True],
 'id1': ['id1', True],
 'id2': ['id2', True],
 'Alert_Rn_Severity_cat': ['alert_rn_severity', True],
 'Response': ['response_reasons_codes', True],
 'Answer_Text_EN': ['response_reasons__selected_text', True],
 'Module_Severity_Rn': ['module_severity_rn', True],
 'Time_Mabat_Request_convert_ms_res': ['mabat_request_time_ms', True],
 'Time_Mabat_Response_convert_ms_res': ['mabat_response_time_ms', True],
 'diff_time_mabat_ms_x': ['response_time', True],
 'DRC_SUB_GROUP': ['dosing_subgroup', True],
 'NeoDRC_SUB_GROUP': ['neodosing_subgroup', True],
 'ATC_cnt': ['atc_count', True],
 'ATC_NEW': ['drug_atc', True],
 'cnt_chronic_id': ['chronic_drug_count', True],
 'Order_ID_new_update': ['drug_order_id', True],
 'NumMedAmount_calc': ['medication_orders_hospatalization', True],
 'num_of_diagnosis': ['diagnosis_count', True],
 'num_of_reception_diagnosis': ['num_of_chronic_diagnosis', True],
 'diseaseSplit': ['disease_split', True],
 'Charlson_score': ['charlson_score', True],
 'Charlson_score_age_adj': ['charlson_score_age_adj', True],
 'SurvivalRate10years_age_adj': ['survival_rate_10y_age_adj', True],
 'adult_child_cat': ['age_group', True],
 'Age_cat': ['age_category', True],
 'drugs_from_AlretMessage': ['drugs_in_alert_message', True],
 'num_of_alerts_per_order_id': ['alerts_per_order_count', True],
 'DAM_CAT': ['allergy', True],
 'DDI_Contraindicated_Drug_Combination_CAT': ['ddi_contraindicated_severity', True],
 'DDI_Moderate_Interaction_CAT': ['ddi_moderate_severity', True],
 'DDI_Severe_Interaction_CAT': ['ddi_severe_severity', True],
 'DRC_CAT': ['dosing', True],
 'Technical_alerts_CAT': ['technical_alerts', True],
 'Renal_alerts_CAT': ['renal_alerts', True],
 'NeoDRC_CAT': ['neo_dosing', True],
 'chronic_num_calc': ['chronic_med_count', True],
 'date_time_prescribe': ['date_time_prescribe', True],
 'hosp_days': ['hospital_days', True],
 'diff_time_mabat_ms_y': ['diff_time_mabat_y', True],
 'DRC - Duration 1': ['dosing_duration', True],
 'DRC_Frequency_1': ['dosing_frequency', True],
 'DRC_Max_Daily_Dose_1': ['dosing_max_daily_dose', True],
 'DRC - Message 1': ['dosing_message', True],
 'DRC_Single_Dose_1': ['dosing_single_dose', True],
 'NeoDRC - Duration 1': ['neo_dosing_duration', True],
 'NeoDRC - Frequency 1': ['neo_dosing_frequency', True],
 'NeoDRC - Max Daily Dose 1': ['neo_dosing_max_daily_dose', True],
 'NeoDRC - Message 1': ['neo_dosing_message', True],
 'NeoDRC - Single Dose 1': ['neo_dosing_single_dose', True],
 'Alert_type': ['alert_type', True],
 'Alert_status': ['alert_status', True],
 'LIVER_count': ['liver_count', True],
 'HEPATIC_count': ['hepatic_count', True],
 'CIRRHOSIS_count': ['cirrhosis_count', True],
 'HEPATITIS_count': ['hepatitis_count', True],
 'PORTAL HYPERTENSION_count': ['portal_hypertension_count', True],
 'JAUNDICE_count': ['jaundice_count', True],
 'MYOCARDIAL_count': ['myocardial_count', True],
 'HEART FAILURE_count': ['heart_failure_count', True],
 'PERIPHERAL VASCULAR DISEASE_count': ['peripheral_vascular _disease_count', True],
 'PVD_count': ['pvd_count', True],
 'CEREBROVASCULAR_count': ['cerebrovascular_count', True],
 'STROKE_count': ['stroke_count', True],
 'CEREBRAL INFARCTION_count': ['cerebral_infarction_count', True],
 'TIA_count': ['tia_count', True],
 'CVA_count': ['cva_count', True],
 'DEMENTIA_count': ['dementia_count', True],
 'CHRONIC PULMONARY DISEASE_count': ['chronic_ pulmonary _disease_count', True],
 'COPD_count': ['copd_count', True],
 'CHRONIC OBSTRUCTIVE PULMONARY DISEASE_count': ['chronic _obstructive _pulmonary _disease_count', True],
 'RHEUMATOLOGIC DISEASE_count': ['rheumatic_disease_count', True],
 'FIBROMYALGIA_count': ['fibromyalgia_count', True],
 'GOUT_count': ['gout_count', True],
 'ARTHRITIS_count': ['arthritis_count', True],
 'ANKYLOSING SPONDYLITIS_count': ['ankylosing_spondylitis_count', True],
 'SCLERODERMA_count': ['scleroderma_count', True],
 'DUODENAL ULCER_count': ['duodenal_ulcer_count', True],
 'PEPTIC ULCER_count': ['peptic_ulcer_count', True],
 'GASTRIC ULCER_count': ['gastric_ulcer_count', True],
 'DIABETES_count': ['diabetes_count', True],
 'HEMIPLEGIA_count': ['hemiplegia_count', True],
 'HEMIPARESIS_count': ['hemiparesis_count', True],
 'PARAPLEGIA_count': ['paraplegia_count', True],
 'RENAL_count': ['renal_count', True],
 'PYELONEPHRITIS_count': ['pyelonephritis_count', True],
 'HEMODIALYSIS_count': ['hemodialysis_count', True],
 'KIDNEY_count': ['kidney_count', True],
 'CKD_count': ['ckd_count', True],
 'ARF_count': ['arf_count', True],
 'AKI_count': ['aki_count', True],
 'MALIGNANCY_count': ['malignancy_count', True],
 'MALIGNANT_count': ['malignant_count', True],
 'CARCINOMA_count': ['carcinoma_count', True],
 'NEOPLASM_count': ['neoplasm_count', True],
 'ADENOCARCINOMA_count': ['adenocarcinoma_count', True],
 'LEUKEMIA_count': ['leukemia_count', True],
 'AML_count': ['aml_count', True],
 'CML_count': ['cml_count', True],
 'LYMPHOMA_count': ['lymphoma_count', True],
 'HIV_count': ['hiv_count', True],
 'METASTATIC_count': ['metastatic_count', True],
 'METASTASIS_count': ['metastasis_count', True],
 'liver_group_cnt': ['liver_group_count', True],
 'PVD_group_cnt': ['pvd_group_count', True],
 'CEREBROVASCULAR_group_cnt': ['cerebrovascular_group_count', True],
 'COPD_group_cnt': ['copd_group_count', True],
 'GOUT_group_cnt': ['gout_group_count', True],
 'ULCER_group_cnt': ['ulcer_group_count', True],
 'HEMIPLEGIA_group_cnt': ['hemiplegia_group_count', True],
 'RENAL_group_cnt': ['renal_group_count', True],
 'MALIGNANCY_group_cnt': ['malignancy_group_count', True],
 'LEUKEMIA_group_cnt': ['leukemia_group_count', True],
 'METASTATIC_group_cnt': ['metastatic_group_count', True],
 'ATC_GROUP': ['atc_group', True],
 'dose_direction_DRC_Frequency_1': ['dosing_frequency_direction', True],
 'dose_direction_DRC_Single_Dose_1': ['dosing_single_dose_direction', True],
 'dose_direction_DRC_Max_Daily_Dose_1': ['dosing_max_daily_dose_direction', True],
 'dose_direction_NeoDRC_Frequency_1': ['neo_dosing_frequency_direction', True],
 'dose_direction_NeoDRC_Single_Dose_1': ['neo_dosing_single_dose_direction', True],
 'dose_direction_NeoDRC_Max_Daily_Dose_1': ['neo_dosing_max_daily_dose_direction', True]
}

rename_keep_dict_false = {
    'HospitalName_cat': ['hospital_name_heb', False],
    'Gender_Text_cat': ['gender_heb', False],
    'SectorText_cat': ['sector_heb', False],
    'Order_ID_new': ['order_id_new', False],
    'Field': ['field', False],
    'IS_New_Order': ['is_new_order', False],
    'DayHebrew_cat': ['day_heb', False],
    'ATC': ['atc', False],
    "'ATC_cln": ['atc_clean', False],
    'Drug_Header_cat_1st_word': ['drug_header_first_word', False],
    'Basic_Name_1st_word': ['basic_name_first_word', False],
    'BASIC_NAME_EXT_1st_wor': ['basic_name_ext_first_word', False],
    'ATC5': ['atc5', False],
    'charls_sum1_3_points': ['charls_sum1_3_points', False],
    'charls_sum2points': ['charls_sum2points', False],
    'charls_sum6points': ['charls_sum6points', False],
    'DAM': ['dam_count', False],
    'DDI_Contraindicated_Drug_Combination': ['ddi_contraindicated_count', False],
    'DDI_Moderate_Interaction': ['ddi_moderate_count', False],
    'DDI_Severe_Interaction': ['ddi_severe_count', False],
    'DDI-Undetermined Severity - Alternative Therapy Interaction': ['ddi_unknown_severity_count', False],
    'DRC': ['drc_count', False],
    'DT': ['dt_count', False],
    'NeoDRC': ['neodrc_count', False],
    'Renal_alerts': ['renal_alerts_count', False],
    'Technical_alerts': ['technical_alerts_count', False]
}

